In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

## Applying Over Housing Data

In [4]:
import pandas as pd 
path = '/Users/sadiakhanrupa/Bootcamp Main Phase/Dr.-Greenthumb-Decoding-Nature-s-Needs/notebooks/housing_iteration_6_regression.csv'

data = pd.read_csv(path)

In [7]:
data.head()
dataset = data.drop(['Id'], axis=1)

In [8]:
dataset.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

# splitting data

In [9]:
X = dataset.copy()
y = X.pop('SalePrice')

In [10]:
X.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [11]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=42)

In [19]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1168 entries, 254 to 1126
Data columns (total 79 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1168 non-null   int64
 1   MSZoning       1168 non-null   object
 2   LotFrontage    951 non-null    float64
 3   LotArea        1168 non-null   int64
 4   Street         1168 non-null   object
 5   Alley          74 non-null     object
 6   LotShape       1168 non-null   object
 7   LandContour    1168 non-null   object
 8   Utilities      1168 non-null   object
 9   LotConfig      1168 non-null   object
 10  LandSlope      1168 non-null   object
 11  Neighborhood   1168 non-null   object
 12  Condition1     1168 non-null   object
 13  Condition2     1168 non-null   object
 14  BldgType       1168 non-null   object
 15  HouseStyle     1168 non-null   object
 16  OverallQual    1168 non-null   int64
 17  OverallCond    1168 non-null   int64
 18  YearBuilt      1168 non-null   int64
 19  YearRemodAdd   1168 non-null   int64
 20  RoofStyle      1168 non-null   object
 21  RoofMatl       1168 non-null   object
 22  Exterior1st    1168 non-null   object
 23  Exterior2nd    1168 non-null   object
 24  MasVnrType     485 non-null    object
 25  MasVnrArea     1162 non-null   float64
 26  ExterQual      1168 non-null   object
 27  ExterCond      1168 non-null   object
 28  Foundation     1168 non-null   object
 29  BsmtQual       1140 non-null   object
 30  BsmtCond       1140 non-null   object
 31  BsmtExposure   1140 non-null   object
 32  BsmtFinType1   1140 non-null   object
 33  BsmtFinSF1     1168 non-null   int64
 34  BsmtFinType2   1140 non-null   object
 35  BsmtFinSF2     1168 non-null   int64
 36  BsmtUnfSF      1168 non-null   int64
 37  TotalBsmtSF    1168 non-null   int64
 38  Heating        1168 non-null   object
 39  HeatingQC      1168 non-null   object
 40  CentralAir     1168 non-null   object
 41  Electrical     1167 non-null   object
 42  1stFlrSF       1168 non-null   int64
 43  2ndFlrSF       1168 non-null   int64
 44  LowQualFinSF   1168 non-null   int64
 45  GrLivArea      1168 non-null   int64
 46  BsmtFullBath   1168 non-null   int64
 47  BsmtHalfBath   1168 non-null   int64
 48  FullBath       1168 non-null   int64
 49  HalfBath       1168 non-null   int64
 50  BedroomAbvGr   1168 non-null   int64
 51  KitchenAbvGr   1168 non-null   int64
 52  KitchenQual    1168 non-null   object
 53  TotRmsAbvGrd   1168 non-null   int64
 54  Functional     1168 non-null   object
 55  Fireplaces     1168 non-null   int64
 56  FireplaceQu    621 non-null    object
 57  GarageType     1104 non-null   object
 58  GarageYrBlt    1104 non-null   float64
 59  GarageFinish   1104 non-null   object
 60  GarageCars     1168 non-null   int64
 61  GarageArea     1168 non-null   int64
 62  GarageQual     1104 non-null   object
 63  GarageCond     1104 non-null   object
 64  PavedDrive     1168 non-null   object
 65  WoodDeckSF     1168 non-null   int64
 66  OpenPorchSF    1168 non-null   int64
 67  EnclosedPorch  1168 non-null   int64
 68  3SsnPorch      1168 non-null   int64
 69  ScreenPorch    1168 non-null   int64
 70  PoolArea       1168 non-null   int64
 71  PoolQC         6 non-null      object
 72  Fence          233 non-null    object
 73  MiscFeature    46 non-null     object
 74  MiscVal        1168 non-null   int64
 75  MoSold         1168 non-null   int64
 76  YrSold         1168 non-null   int64
 77  SaleType       1168 non-null   object
 78  SaleCondition  1168 non-null   object
dtypes: float64(3), int64(33), object(43)
memory usage: 730.0+ KB

## Converting into tensor